services:
  - type: web
    name: smart-chatbot
    env: python
    buildCommand: pip install -r requirements.txt && python train_lstm.py
    startCommand: gunicorn app:app --timeout 120 --workers 1 --threads 2 --worker-class gthread --max-requests 1000 --max-requests-jitter 50
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3
